//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VOP.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;items&quot;:[{&quot;service_station_id&quot;:&quot;30&quot;,&quot;user_id&quot;:&quot;0&quot;,&quot;service_station_name&quot;:&quot;\u5357\u5b81\u5e02\u5143\u8054\u79d1\u6280\u6709\u9650\u8d23\u4efb\u516c\u53f8&quot;,&quot;service_station_province&quot;:&quot;\u5e7f\u897f&quot;,&quot;service_station_city&quot;:&quot;\u5357\u5b81&quot;,&quot;service_station_address&quot;:&quot;\u5357\u5b81\u5e02\u53cc\u62e5\u8def9-15\u53f7\u8054\u60f3\u670d\u52a1\u94fa\u9762&quot;,&quot;service_station_product_line&quot;:&quot;&quot;,&quot;service_station_phone&quot;:&quot;0771-5304889&quot;,&quot;service_station_hours&quot;:&quot;&quot;,&quot;service_station_remark&quot;:&quot;&quot;,&quot;service_station_longitude&quot;:&quot;108.35808 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaintainInfo_Json {
            get {
                return ResourceManager.GetString("MaintainInfo_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;items&quot;:[{&quot;merchant_id&quot;:&quot;121&quot;,&quot;user_id&quot;:&quot;2&quot;,&quot;merchant_code&quot;:&quot;111231148&quot;,&quot;merchant_name&quot;:&quot;\u6e56\u5357\u950b\u884c\u4fe1\u606f\u79d1\u6280\u6709\u9650\u516c\u53f8&quot;,&quot;merchant_email&quot;:&quot;947409712@163.com&quot;,&quot;merchant_image&quot;:&quot;http:\/\/o2o.iprintworks.cn\/uploads\/t\/201409\/0313524071121.jpg&quot;,&quot;merchant_password&quot;:&quot;5c3ea2db15f058a43fa662e0b0fdfe6f&quot;,&quot;merchant_type&quot;:&quot;printer&quot;,&quot;merchant_product_category&quot;:&quot;printer,supplies&quot;,&quot;merchant_phone&quot;:&quot;13874149545&quot;,&quot;merchant_contact&quot;:&quot;&quot;,&quot;merchant_province&quot;:&quot;\u6e56\u5357\u7701&quot;,&quot;me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MerchantInfo_Json {
            get {
                return ResourceManager.GetString("MerchantInfo_Json", resourceCulture);
            }
        }
    }
}
