//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VOP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行卡/社保卡.
        /// </summary>
        public static string SID_BankCards {
            get {
                return ResourceManager.GetString("SID_BankCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出生证明.
        /// </summary>
        public static string SID_BirthCertificate {
            get {
                return ResourceManager.GetString("SID_BirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毕业证.
        /// </summary>
        public static string SID_Diploma {
            get {
                return ResourceManager.GetString("SID_Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驾照.
        /// </summary>
        public static string SID_DriverLicense {
            get {
                return ResourceManager.GetString("SID_DriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 户口本.
        /// </summary>
        public static string SID_HouseholdRegister {
            get {
                return ResourceManager.GetString("SID_HouseholdRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证.
        /// </summary>
        public static string SID_IdCard {
            get {
                return ResourceManager.GetString("SID_IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结婚证.
        /// </summary>
        public static string SID_MarriageCertificate {
            get {
                return ResourceManager.GetString("SID_MarriageCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 护照.
        /// </summary>
        public static string SID_Passport {
            get {
                return ResourceManager.GetString("SID_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房产证.
        /// </summary>
        public static string SID_RealEstateEvaluator {
            get {
                return ResourceManager.GetString("SID_RealEstateEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生证.
        /// </summary>
        public static string SID_StudentIDcard {
            get {
                return ResourceManager.GetString("SID_StudentIDcard", resourceCulture);
            }
        }
    }
}
